// Phase 653 – the Go sessions page (recorded replay + BYOS live-connect).
//
// Two gates, both headless via vitest:
//   1. The recorded replay artefact (regenerated by the demo binary's --record)
//      round-trips through the page's loader: it parses, has the expected frames,
//      and every frame's resolved-projection wire decodes through the real Fuaran
//      decoder (i.e. it is renderable).
//   2. The BYOS client logic (URL/body builders + envelope parsing + the async
//      fetch functions) is covered against a stubbed local endpoint, including the
//      typed-reject and connection-refused legs. (The live-connect leg against a
//      real binary is a manual checklist item for the operator.)

import { createServer, type Server } from 'node:http';
import { readFileSync } from 'node:fs';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// @ts-expect-error untyped Fable output
import * as GS from '../app/showcase/output/GoSessions.js';
// The real Fuaran decoder, from the packaged language tier – see test/tierOutput.ts.
import { decodeNode } from './tierOutput.js';

const artefactJson = readFileSync('public/replays/go-sessions.json', 'utf8');

describe('Phase 653 – recorded replay artefact round-trips through the loader', () => {
  const art = GS.parseArtefact(artefactJson);

  it('parses and carries the four scripted frames', () => {
    expect(art).not.toBeNull();
    expect(GS.frameCount(art)).toBe(4);
  });

  it('records the scripted interaction sequence in order', () => {
    expect(GS.frameActionKind(art, 0)).toBe('load');
    expect(GS.frameActionKind(art, 1)).toBe('setState');
    expect(GS.frameActionKind(art, 2)).toBe('applyOp');
    expect(GS.frameActionKind(art, 3)).toBe('applyOp');
    for (let i = 0; i < 4; i++) expect(GS.frameLabel(art, i).length).toBeGreaterThan(0);
  });

  it('marks only the last frame as a validator reject, with a typed code', () => {
    expect(GS.frameIsReject(art, 0)).toBe(false);
    expect(GS.frameIsReject(art, 2)).toBe(false);
    expect(GS.frameIsReject(art, 3)).toBe(true);
    expect(GS.frameRejectCode(art, 3).length).toBeGreaterThan(0);
  });

  it('every frame decodes through the real Fuaran decoder (renderable)', () => {
    for (let i = 0; i < GS.frameCount(art); i++) {
      const wire = GS.frameResolvedJson(art, i);
      expect(wire.length).toBeGreaterThan(0);
      const r = decodeNode(wire);
      expect(r.tag).toBe(0); // 0 = Ok
    }
  });

  // The artefact is COMMITTED to a public repository and is GENERATED by a demo
  // binary run on a maintainer's machine, so it is exactly the kind of file that
  // carries something across without anybody looking. Two checks, and the split
  // is the point.
  //
  // The configurable half reads a deny-list from FUARAN_DENY_LIST (one pattern
  // per line, '#' comments ignored — the shape the maintainers' boundary lint
  // uses, materialised in CI from a secret). The list is NOT written here: this
  // file is published, and a test that spells out the vocabulary it exists to
  // keep off the public surface has put that vocabulary on the public surface.
  // That is not hypothetical — the list stood here verbatim until Phase 1676.
  //
  // The unconditional half needs no list and leaks nothing, because it names a
  // SHAPE rather than a word: a recorded replay is a tree, a sequence of actions
  // and their labels, so an absolute filesystem path or a non-loopback URL in it
  // is a fact about the recorder's machine with no business being here. It holds
  // on a fork PR, on a fresh clone and on a machine with no configuration at all
  // — which is exactly where the list-driven half cannot help.

  const denyPatterns = (process.env['FUARAN_DENY_LIST'] ?? '')
    .split(/[\r\n,]+/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));

  it('carries no absolute filesystem path and no off-machine URL', () => {
    // A Windows drive path, a POSIX home/system path, and any URL whose host is
    // not loopback. A recorded session legitimately names 127.0.0.1 endpoints.
    expect(artefactJson.match(/[A-Za-z]:[\\/][A-Za-z0-9_.-]{2,}/g) ?? []).toEqual([]);
    expect(artefactJson.match(/\/(?:home|Users|root|mnt)\/[A-Za-z0-9_.-]{2,}/g) ?? []).toEqual([]);
    const offMachine = (artefactJson.match(/https?:\/\/[^"'\s\\]+/g) ?? []).filter(
      (url) => !/^https?:\/\/(?:localhost|127\.0\.0\.1|\[::1\])(?::\d+)?(?:[/?#]|$)/.test(url),
    );
    expect(offMachine).toEqual([]);
  });

  it.skipIf(denyPatterns.length === 0)(
    'carries nothing the configured publication deny-list names',
    () => {
      // Reported by INDEX, never by text: a failure message echoing the pattern
      // would put it in a public CI log, which is the same leak one step later.
      const lower = artefactJson.toLowerCase();
      const hits = denyPatterns
        .map((pattern, index) => ({ index, hit: new RegExp(pattern, 'i').test(lower) }))
        .filter((row) => row.hit)
        .map((row) => `deny-list entry #${row.index + 1}`);
      expect(hits).toEqual([]);
    },
  );
});

describe('Phase 653 – BYOS client: pure request builders + envelope parsing', () => {
  it('builds the versioned endpoint URLs, trimming a trailing slash', () => {
    expect(GS.sessionUrl('http://localhost:14050')).toBe('http://localhost:14050/api/v1/session');
    expect(GS.stateUrl('http://localhost:14050/')).toBe('http://localhost:14050/api/v1/state');
    expect(GS.opUrl('http://localhost:14050')).toBe('http://localhost:14050/api/v1/op');
  });

  it('builds request bodies with the value/op embedded as raw JSON', () => {
    expect(JSON.parse(GS.stateRequestBody('revenue', '7500'))).toEqual({
      key: 'revenue',
      value: 7500,
    });
    expect(JSON.parse(GS.opRequestBody('{"$type":"NoOp"}'))).toEqual({ op: { $type: 'NoOp' } });
  });

  it('parses the ok / reject / error / refused envelopes', () => {
    const ok = GS.parseApiResponse(
      200,
      JSON.stringify({ version: 'v1', ok: true, resolved: { id: 'x' } }),
    );
    expect(ok.kind).toBe('ok');
    expect(ok.resolved).toContain('"id":"x"');

    const rej = GS.parseApiResponse(
      200,
      JSON.stringify({
        version: 'v1',
        ok: false,
        reject: { code: 'FUARAN_X', message: 'no' },
        resolved: { id: 'y' },
      }),
    );
    expect(rej.kind).toBe('reject');
    expect(rej.rejectCode).toBe('FUARAN_X');
    expect(rej.resolved).toContain('"id":"y"'); // the kept last-good tree

    expect(
      GS.parseApiResponse(500, JSON.stringify({ version: 'v1', ok: false, error: 'boom' })).kind,
    ).toBe('error');
    expect(GS.parseApiResponse(200, 'not json').kind).toBe('error');
    expect(GS.parseApiResponse(0, 'ECONNREFUSED').kind).toBe('refused');
  });
});

describe('Phase 653 – BYOS client vs a stubbed local endpoint', () => {
  let server: Server;
  let base = '';

  const seed = { id: 'dashboard', kind: { $type: 'Box', role: 'Dashboard', children: [] } };
  const edited = {
    id: 'dashboard',
    kind: { $type: 'Box', role: 'Dashboard', children: ['edited'] },
  };

  const send = (res: import('node:http').ServerResponse, obj: unknown) => {
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify(obj));
  };

  beforeAll(async () => {
    server = createServer((req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (c) => chunks.push(c));
      req.on('end', () => {
        const body = Buffer.concat(chunks).toString();
        if (req.url === '/api/v1/session') {
          send(res, { version: 'v1', ok: true, resolved: seed });
        } else if (req.url === '/api/v1/state') {
          send(res, { version: 'v1', ok: true, resolved: seed });
        } else if (req.url === '/api/v1/op') {
          if (body.includes('NotAKind')) {
            // A validator reject: ok:false + typed reject + the kept last-good tree.
            send(res, {
              version: 'v1',
              ok: false,
              reject: { code: 'FUARAN_STUB_REJECT', message: 'unknown kind' },
              resolved: edited,
            });
          } else {
            send(res, { version: 'v1', ok: true, resolved: edited });
          }
        } else {
          res.statusCode = 404;
          res.end();
        }
      });
    });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    const addr = server.address();
    if (addr && typeof addr === 'object') base = `http://127.0.0.1:${addr.port}`;
  });

  afterAll(() => new Promise<void>((resolve) => server.close(() => resolve())));

  it('GET session returns ok + the resolved projection', async () => {
    const r = await GS.byosGetSession(base);
    expect(r.kind).toBe('ok');
    expect(r.resolved).toContain('"role":"Dashboard"');
  });

  it('POST state succeeds', async () => {
    const r = await GS.byosPostState(base, 'revenue', '7500');
    expect(r.kind).toBe('ok');
  });

  it('POST a valid op re-projects the change', async () => {
    const r = await GS.byosPostOp(
      base,
      '{"$type":"EditNode","newKind":{"$type":"Box"},"target":"x"}',
    );
    expect(r.kind).toBe('ok');
    expect(r.resolved).toContain('edited');
  });

  it('POST an invalid op surfaces a typed reject with the kept last-good tree', async () => {
    const r = await GS.byosPostOp(
      base,
      '{"$type":"EditNode","newKind":{"$type":"NotAKind"},"target":"x"}',
    );
    expect(r.kind).toBe('reject');
    expect(r.rejectCode).toBe('FUARAN_STUB_REJECT');
    expect(r.resolved).toContain('edited'); // last-good tree still returned
  });

  it('a refused connection fails soft to the refused outcome', async () => {
    // Port 1 is never listening → the fetch rejects → parseApiResponse maps it to refused.
    const r = await GS.byosGetSession('http://127.0.0.1:1');
    expect(r.kind).toBe('refused');
  });
});
