// The prompt-sourcing drift lock.
//
// The playground's system prompt (app/SystemPrompt.fs) is COMPOSED: the
// language repo's drift-checked AI-authoring prompt pack
// (fuaran/docs/prompt-pack/system-prompt.md — the exact system prompt the
// published evaluation measured, corpus-generated examples, regenerated by
// authoring-pack.fsx) inlined byte-for-byte via a Vite `?raw` sibling import,
// plus a small chat-surface overlay (reply protocol, CodeBlock/Math teaching,
// the measured Frugality posture).
//
// This lock is what makes the sourcing PERMANENT rather than aspirational: if
// the F# module ever stops importing the pack (a refactor back to hand-copied
// prose), or the sibling pack regenerates and the compiled output goes stale,
// the byte-prefix assertion reds. The teaching canaries pin the two
// eval-proven fixes (pilot 5: Selection.defaultValue 0/9 → 30/30; "Filters
// must be WIRED" campaign-wide miss → 84%) so the measured teachings can never
// silently drop out of what the playground sends.
//
// Requires `pnpm run fable:app` to have produced app/output/ (same as
// closedLoop.test.ts, whose every-fence lock certifies the composed prompt's
// examples through the app's real decode/apply loop).

import { describe, it, expect } from 'vitest';

// @ts-expect-error untyped Fable output
import { value as systemPrompt } from '../app/output/SystemPrompt.js';
// The same sibling file the F# module inlines — resolved by the same Vite
// pipeline, so this comparison is against the CURRENT pack bytes on disk.
import packRaw from '../../fuaran/docs/prompt-pack/system-prompt.md?raw';

describe('the system prompt is sourced from the drift-checked prompt pack', () => {
  it('starts with the sibling pack bytes (the ?raw inline is live, not a copy)', () => {
    expect(packRaw.trim().length).toBeGreaterThan(10_000);
    expect(systemPrompt.startsWith(packRaw.trim())).toBe(true);
  });

  it('carries the eval-proven teachings (pilot-5 fix-deltas)', () => {
    // 040/c3 — pre-selected rows via Selection.defaultValue.
    expect(systemPrompt).toContain('defaultValue');
    // 035/c7 — declaring filters is not enough; they must be wired.
    expect(systemPrompt).toContain('Filters must be WIRED');
  });

  it('keeps the chat-surface overlay after the pack teaching', () => {
    const protocol = systemPrompt.indexOf("This playground's chat protocol");
    const frugality = systemPrompt.indexOf('# Frugality');
    expect(protocol).toBeGreaterThan(packRaw.trim().length - 1);
    expect(frugality).toBeGreaterThan(protocol);
  });
});
