// Phase 85 – the F# (Fable) render-host iframe entry.
//
// Thin TS shim for fable-host.html. It pulls in the canonical reference CSS
// (the SAME `@fuaran-ui/renderer/css` byte-copy the TS host loads – the
// Phase 77 parity-lock means both hosts key off one stylesheet) and then
// imports the Fable-compiled host bundle, which self-boots its Elmish program
// (Program.run at module scope in Host.fs) and wires the postMessage listener.
//
// The Fable output is produced by `dotnet fable fable-host` (see
// docs/DUAL_HOST.md). It is gitignored – the committed source is Host.fs.

import '@fuaran-ui/renderer/css';
import 'katex/dist/katex.min.css';
// The icon-contract glyph map — rendered trees carry empty data-icon hooks;
// this maps the common names to currentColor SVG masks.
import '../../app/icon-glyphs.css';

// eslint-disable-next-line import/no-unresolved -- generated by `dotnet fable`
import '../../fable-host/output/Host.js';
