import { defineConfig } from 'vitest/config';

// Conformance suite config — separate from vitest.config.ts (the unit tests).
// The codegen-conformance harness lives under tests/projection-conformance/ and
// executes source generated by the F#/Fable projector (app/Projection.fs) against
// the real @fuaran-ui/* packages, asserting a byte-identical re-encode over the
// workspace wire-format-fixtures corpus. Requires `pnpm run fable:app` first.
// Run via `pnpm conformance` and as a CI gate.
export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/projection-conformance/**/*.test.ts'],
    testTimeout: 120_000,
  },
});
